--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/pjz9n-pm-pl/AliasLogin
build-by-default: true
branches:
  - master
projects:
  AliasLogin:
    path: ""
    libs:
      - src: CortexPE/Commando/Commando
        version: 2.1.1
...
