name: AliasLogin
version: 1.0.0
main: pjz9n\aliaslogin\Main
api: 3.0.0

permissions:
  aliaslogin.command.aliaslogin:
    default: op
  aliaslogin.command.aliaslogin.cancel:
    default: true
  aliaslogin.command.aliaslogin.now:
    default: true
